version: "3"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlji_dev
    volumes:
      - ".local/postgres/data:/var/lib/postgresql/data"
      - ".local/postgres/socket:/var/run/postgresql"